
server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://3.37.155.50:5432/scm
    username: admin
    password: 1234
    platform: postgres


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  application:
    name: contract-service






